FROM opensuse/tumbleweed
RUN zypper in -y cmake ninja gcc-c++ clang-tools extra-cmake-modules qt6-base-devel qt6-tools-devel kf6-kcoreaddons-devel kf6-ki18n-devel kf6-kwallet-devel kf6-knotifications-devel kf6-kxmlgui-devel kf6-kconfig-devel kf6-kwidgetsaddons-devel kf6-kglobalaccel-devel kf6-karchive-devel git
WORKDIR /app
COPY . .
RUN cmake -B build -G Ninja && cmake --build build
