FROM opensuse/tumbleweed
RUN zypper --gpg-auto-import-keys rr repo-openh264 || true && zypper --gpg-auto-import-keys ref && zypper --gpg-auto-import-keys -n dup --allow-downgrade --allow-vendor-change && zypper --gpg-auto-import-keys -n in --auto-agree-with-licenses cmake gcc-c++ ninja kf6-extra-cmake-modules qt6-base-devel qt6-tools-devel qt6-declarative-devel kf6-kcoreaddons-devel kf6-ki18n-devel kf6-kwallet-devel kf6-knotifications-devel kf6-kxmlgui-devel kf6-kconfig-devel kf6-kwidgetsaddons-devel kf6-kglobalaccel-devel kf6-karchive-devel git dbus-1 xvfb-run
COPY . /src
WORKDIR /src
RUN rm -rf build && cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release -DQT_MAJOR_VERSION=6 && cmake --build build --parallel && cd build && QT_QPA_PLATFORM=offscreen ctest --output-on-failure
